[01,02,03] Авторизация, регистрация и выход из профиля
TailsSavarin/airbnb-clone pull request #1
Opened 2022-11-22 19:30 UTC by Eelllllyy

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/App.vue
> +</script>
так как у нас vue 3, я бы тут снизил когнитивную нагрузку и написал бы через скрипт сетап:

```
<script setup>
import Navbar from '@/components/Navbar.vue';
</script>
```

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/assets/styles/application.css
> +}
чтобы не приходилось переназначать глобальные стили для тэгов, которые не наследуют от бади, лучше заменить запись `html, body { ... }` на `* { ... }` `*`- селектор всех всех элементов на странице
Вообще, лучше сразу сбросить все дефолтные стили у самых "застилизованных" элементов, например, написав для тэга `ul` следующие правила (пример):
```
ul {
  list-style-type: none;
}
```
Тут дело в том, что, в 99% случаев, ты везде, где будешь использовать тэг `ul`, будешь писать это.
[Вот пример файла с дефолтными стилями](https://github.com/evgeniyGusev/vue3_math-3_game/blob/master/src/assets/scss/global.scss)
Так же есть [глобальные решения](https://necolas.github.io/normalize.css/8.0.1/normalize.css)

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +  <div @click.capture="startPosEmail">
1. что значит `Pos`? Названия методов должны быть максимально описательными. То есть, прочитав название, должно быть понятно что он делает.
2. зачем тут модификатор `.capture`?
3. html-тэги можно так же сделать интуитивно понятными благодаря классам. Даже если ты не собираешься обращаться к классу, все равно его наличие сделает более понятным смысл использования тэга, тем более если это `div`
4. `@click` на рутовом элементе выглядит сомнительно. Зачем это сделано?

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +      @click.capture="startPosPassword"
не понятное название метода

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +        />
тут пустой див с обработчиком события `click`. Лучше использовать `button`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +        <h2 style="margin-bottom: 20px">
Инлайновые стили лучше не использовать, их невозможно "перебить". Лучше вынести стили в `style` и стилизовать через селектор класса

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +          @keyup="moveLabelforEmail"
есть ощущение, что этот метод можно вызывать у инпута на событии фокуса: `input@focus`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +          @keyup="moveLabelforPassword"
на фокус инпуту

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +            class="input two"
класс `two`? Что значит `two`? Лучше давать более осознанные названия классам

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +        <p style="font-size: 12px">
убрать инлайновые стили

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +          <p class="error">
для отображения ошибки должно быть условие, а тут она всегда отображается?

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +</template>
по темплейту в целом: переписать с использованием семантических тэгов + испльзовать тэг `form`
https://htmlacademy.ru/blog/articles/semantics

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +  if (await storeAuth.handleSubmit()) {
в условии `if()` должно содеражаться простейшее значение, которое легко привести в логическому true или false.
Здесь необходимо вынести ожидание промиса и проверять его результат:
```
const result = await storeAuth.handleSubmit()

if (result) { ... }
```

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +}
Таких вещей быть не должно в компоненте. Для динамического присвоения классов у вью есть динамические классы :)

[вот, нужно прочитать доку](https://vuejs.org/guide/essentials/class-and-style.html#binding-html-classes:~:text=And%20the%20following%20template%3A)

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +  }
используем динамические классы

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +}
используем динамические классы

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +}
используем динамические классы

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/DialogSignUp.vue
> +</style>
Объединить этот компонент и `DialogLogin` в один. Это две точные копии с незначительными изменениями

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +      />
Здесь лучше спользовать семантический тэг `img`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +      </div>
почему клик на диве, если внутри него есть кнопка, которая создана для кликов? :D

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +            <p style="border-bottom: 2px solid black">
убрать инлайновые стили

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +              </div>
Используем тэг `form` для размещения контента, в который пользователь может вводить данные

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +      </div>
заменить на `button`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +          </p>
Заменить на кнопки

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +          style="height: 60px"
Избавиться от инлайновых стилей

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +          </p>
заменить на кнопку

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +    <div :class="{ darkBlock: storeAuth.dialogLogin || storeAuth.dialogSignUp }">
названия классов пишем так же, как мы их именуем инлайново: `:class="{ 'dark-block': storeAuth.dialogLogin || storeAuth.dialogSignUp }"`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +}
достаточно одной переменной для контроля "Открытости" - `isSearchOpen:  false | true`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +  if (storeAuth.isAuth == false) {
1. Сравнения ТОЛЬКО строгие без приведения типов: [`===`](https://learn.javascript.ru/comparison#:~:text=%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D1%81%D1%82%D1%80%D0%BE%D0%B3%D0%BE%D0%B3%D0%BE%20%D1%80%D0%B0%D0%B2%D0%B5%D0%BD%D1%81%D1%82%D0%B2%D0%B0%20%3D%3D%3D%20%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D1%8F%D0%B5%D1%82%20%D1%80%D0%B0%D0%B2%D0%B5%D0%BD%D1%81%D1%82%D0%B2%D0%BE%20%D0%B1%D0%B5%D0%B7%20%D0%BF%D1%80%D0%B8%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F%20%D1%82%D0%B8%D0%BF%D0%BE%D0%B2.)
2. Там, где все приводится к булевому значению (true | false), существует понятие `truthy` и `falsy` значений. Например, `false, 0, null, undefined, '', NaN` - это всё `falsy`, остальное - `truthy` . Это значит, что не надо делать сравнение с ними в проверках. Например, тебе нужно проверить, если `variable` не существует или там пусто или ничего нет, то ты просто можешь написать `if (!variable)`

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/components/Navbar.vue
> +</script>
что это и зачем

2022-11-24 06:45 UTC, evgeniyGusev commented on app/javascript/modules/pages/Main.vue
> +  />
button

2022-11-24 07:07 UTC, TailsSavarin reviewed
Нужны доработки!

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +      <p style="font-size: 12px;">We’ll call or text you to confirm your number. Standard message and data rates apply. Privacy Policy</p>
`Privacy Policy` - это ссылка, подчеркивание снизу и текст жирный (см оф сайт)

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    <div class='block-three' ></div>
Куда двойные кавычки потерялись?

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    <div class='block-three' ></div>
Лишний пробел после кавычек

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/App.vue
> +    <router-view></router-view>
Можно написать просто `<router-view />`

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/App.vue
> +
Пробел

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    <div class="block-two" >
Лишний пробел после класса

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +  <div class="login-block" @click.capture="startPosPassword" >
Лишний пробел после клика

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    <div><button class="btn" @click="submitResult"> Continue </button></div>
Зачем тут пробелы `_Continue_`

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    console.log('rrr')
Это что?

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    position: fixed;
4 пробела???

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    top:10px;
Где пробел потеряла?

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +const moveLabelforEmail = () => {
Сюда в качестве параметра стоит передавать строчку с `'email'`, либо `'password'`. Тогда можно будет избавиться от лишнего метода `moveLabelforPassword`

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +const startPosEmail = () => {
Тут тоже самое, что и вышел

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    top:20px;
Пробелы

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    margin:10px 0 6px 0;
Пробелы

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +    border:none;
Пробелы

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogSignUp.vue
> +<div  @click.capture="startPosName">
Почем после дива два пробела?

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogSignUp.vue
> +  <div  @click.capture="startPosPassword">
Почем после дива два пробела?

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogSignUp.vue
> +      <div class="block-two" >
Лишний пробел после класса

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogSignUp.vue
> +    <div><button class="btn" @click="storeAuth.createUser"> Continue </button></div>
Зачем тут пробелы `_Continue_`

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/DialogLogin.vue
> +      <div class="block-one">
Я бы подумал над названием класса
`block-one/two/three` - звучит сомнительно

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/modules/routes/index.js
> +export const mainRoutes = [
А есть additional?

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/modules/pages/Lodging.vue
> +        <div class="cont-fot-pict-2">
Название странное

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/modules/pages/Lodging.vue
> +          <div class="plDec-two">
😢

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/Navbar.vue
> +/* .open-action-logout{
Комментариев быть не должно

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/Navbar.vue
> +  /* border:1px solid rgba(88, 88, 88, 0.308) */
Комментариев быть не должно

2022-11-24 07:07 UTC, TailsSavarin commented on app/javascript/components/Navbar.vue
> +  /* cursor: pointer; */
Комментариев быть не должно

2022-11-24 11:29 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +  /* border:1px solid rgba(88, 88, 88, 0.308) */
Удалила

2022-11-24 11:45 UTC, Eelllllyy commented on app/javascript/App.vue
> +
А что не так с пробелом? Добавила тут у margin

2022-11-24 12:15 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +  <div @click.capture="startPosEmail">
pos-position , типа стартовая позиция эмэйла. Не получилось придумать более логичное объяснение этого( Попробую чем-то заменить. 
Там логика такая, что когда кликаешь на инпут, лэйбл меняет свое положение, а когда куда-то вне - возвращается обратно. И поэтому я повесила это на див, в котором все лежит.  Не получилось написать две функции на один клин, поэтому несколько раз все обернуто в разные дивы. 
А почему capture, как я поняла , чтобы остановить погружение (??) Иначе оно не работало, поэтому оставила с ним.

2022-11-24 12:22 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +        />
Там в классе background-image картинка крестика. А если сделать вместо дива кнопку , придется доп стилизовать. Все равно лучше заменить или оставить?

2022-11-24 12:35 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +  <div @click.capture="startPosEmail">
Можно тогда порассуждать над событиями самого инпута. Если мы в состоянии, в котором можем что-то в него писать, значит он выкинул событие focus, а когда мы изменили состояние из возможности писать в НЕвозможность - инпут выкинул blur. Я так написал, потому что этого можно добиться различными способами: клик по инпуту а потом вне его; кнопка tab; клик за окном браузера; кнопка enter и тд. Во всех этих случаях твой код не сработает

2022-11-24 12:36 UTC, evgeniyGusev commented on app/javascript/components/DialogLogin.vue
> +        />
Лучше написать стили, чем заставлять НЕкнопку быть кнопкой))

2022-11-24 12:46 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +        <h2 style="margin-bottom: 20px">
Везде поменяла.
А если допустим надо добавить всего один отступ , то все равно лучше будет вынести в класс ?

2022-11-24 12:53 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +          @keyup="moveLabelforEmail"
В плане заменить keyup?

2022-11-24 15:29 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +          <p class="error">
Добавила v-if="storeAuth.error"

2022-11-24 15:30 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +            class="input two"
Заменила на border-radius-bottom и border-radius-top

2022-11-24 15:34 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +        />
Не буду абьюзером - напишу стили 👍

2022-11-25 14:13 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +}
Заменила на :
const isActiveLabelEmail = ref(false)
const moveLabelforEmail = () => {
  isActiveLabelEmail.value = true
}   // функция при нажатии на инпут 
 
и выше:
:class="{'move-label': isActiveLabelEmail}"

2022-11-25 14:26 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +      </div>
Поменяла))))))

2022-11-25 14:48 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +          </p>
То есть везде где надо кликать лучше заменить на кнопки ?

2022-11-25 15:13 UTC, Eelllllyy commented on app/javascript/components/DialogLogin.vue
> +      @click.capture="startPosPassword"
Написала вот так : returnLabelforEmail
Лучше или еще подумать ?

2022-11-25 15:23 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +</script>
Удалила..

2022-11-26 15:46 UTC, TailsSavarin requested changes
Изменить размер логотипа, а также увеличить размер навбара, см офф сайт, добавить валидации, добавить тосты (уведомления), решить вопрос с пагинацией и переходом в картинках у карточек

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/assets/styles/application.css
> +html, body {
Так надо было поменять тут, а не в App.vue

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/App.vue
> +*{
Это должно быть в `app/javascript/assets/styles/application.css`

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/DialogLoginOrSignUp.vue
> +            <div v-if="(storeAuth.dialogLogin === true && storeAuth.dialogSignUp === false) ">
Тебе же говорили про truthy / falsy. Надо поменять...

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/Footer.vue
> +        <p class="dats">
Что такое dats? Это на каком языке?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/DialogLoginOrSignUp.vue
> +              <input
Глазик где? mdi-icons
Открытый и закрытый
Для логина тоже добавить

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/Footer.vue
> +        <p class="unvis">
Что такое unvis?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/Footer.vue
> +        <p />
![image](https://user-images.githubusercontent.com/57631057/204096044-c4f050fd-a9b4-4d35-a8cf-36d1eb6fb774.png)

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/Footer.vue
> +<script setup>
Зачем тут script?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/FooterDeploed.vue
> +        <p class="dats">
dats?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/FooterDeploed.vue
> +<script setup>
Зачем это тут?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/Navbar.vue
> +const loginOpen = () => {
Какое-то странное условие

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/components/Navbar.vue
> +const loginOpen = () => {
Подумай, как можно оптимальней написать

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/modules/pages/Stays.vue
> +        <div class="container-for-img-2">
Очень странно называешь for img-2, а там внутри img-2/3/4/5

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +        VueCookies.set('token', response.data.access, 60, null, null, true)
60 seconds?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +    async createUser() {
А тут мы разве токен не получаем, кто его сохранять будет?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +        VueCookies.set('token', response.data.access, 60, null, null, true)
Помимо этого ты должна сохранять рефрешь токен

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +        VueCookies.set('token', response.data.access, 60, null, null, true)
Логики с обработкой рефрешь токена нет :(

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          this.totalPages = Math.ceil(response.headers['total-count'] / this.items)
Что это за фигня?

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          this.totalPages = Math.ceil(response.headers['total-count'] / this.items)
Тебе в хедере приходит:
Current-Page
Page-Items
Total-Count
Total-Pages

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          console.log(response)
console.log

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          console.log(this.cards)
console.log

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          this.page += 1;
this.page++

2022-11-26 15:46 UTC, TailsSavarin commented on package.json
> +    "v3-infinite-loading": "^1.2.2",
Удали, если не используешь

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          const response = await axios.get('/api/stays',{
А если у тебя кол-во страниц изменится, этот момент не продуман, тебе в каждом запросе в хедерах приходит мета информация

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          const response = await axios.get('/api/stays',{
Поэтому можно избавиться от `this.page += 1;`
И подставлять туда информацию из хедера

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          const response = await axios.get('/api/stays',{
Потому что если вдруг запрос упадет, то this.page у тебя будет уже +1

2022-11-26 15:46 UTC, TailsSavarin commented on app/javascript/store/store.js
> +          this.cards = [...this.cards,...response.data]
Не совсем понимаю, зачем ты перезаписываешь массив с `cards`, может быть есть смысл туда просто добавить новые элементы через `.push`

2022-11-26 17:18 UTC, Eelllllyy commented on app/javascript/assets/styles/application.css
> +html, body {
Не поняла тебя, это как ты сделал , так и осталось с шрифтами этими..

2022-11-26 17:21 UTC, Eelllllyy commented on app/javascript/App.vue
> +*{
Поместила

2022-11-26 17:21 UTC, Eelllllyy commented on app/javascript/components/DialogLoginOrSignUp.vue
> +            <div v-if="(storeAuth.dialogLogin === true && storeAuth.dialogSignUp === false) ">
точно

2022-11-26 17:24 UTC, Eelllllyy commented on app/javascript/components/DialogLoginOrSignUp.vue
> +            <div v-if="(storeAuth.dialogLogin === true && storeAuth.dialogSignUp === false) ">
Заменила на v-if="(storeAuth.dialogLogin && !storeAuth.dialogSignUp)"

2022-11-26 17:25 UTC, Eelllllyy commented on app/javascript/components/Footer.vue
> +        <p class="dats">
На датском *шучу
Лучше не спрашивать, сейчас поменяю

2022-11-26 17:30 UTC, Eelllllyy commented on app/javascript/components/Footer.vue
> +        <p class="unvis">
поменяла

2022-11-26 17:32 UTC, Eelllllyy commented on app/javascript/components/Footer.vue
> +        <p />
так в макете ... правда.... 
по моему симпатичней чем and 
Не?

2022-11-26 17:34 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +const loginOpen = () => {
Ты про 120 и 121 строки? То что с кнопкой невидимой той

2022-11-26 17:34 UTC, Eelllllyy commented on app/javascript/modules/pages/Stays.vue
> +        <div class="container-for-img-2">
ну типа второй контейнер 
До этого был первый
как-то придумаю тогда и заменю

2022-11-26 17:35 UTC, Eelllllyy commented on app/javascript/modules/pages/Stays.vue
> +        <div class="container-for-img-2">
а если вместо 1 и 2 first second - так лучше ?

2022-11-26 17:37 UTC, Eelllllyy commented on app/javascript/store/store.js
> +    async createUser() {
почему-то мне казалось что оно само сохранится, после твоей фразы что ты добавил.. только сейчас дошло , добавила сет куки

2022-11-26 17:38 UTC, Eelllllyy commented on app/javascript/store/store.js
> +          this.totalPages = Math.ceil(response.headers['total-count'] / this.items)
я кстати на них посмотрела , хотела спросить , но забыла

2022-11-26 17:45 UTC, Eelllllyy commented on app/javascript/store/store.js
> +          this.cards = [...this.cards,...response.data]
Попробую

2022-11-26 17:51 UTC, Eelllllyy commented on app/javascript/store/store.js
> +          this.cards = [...this.cards,...response.data]
чего-то оно так ошибку выдает

2022-11-26 18:01 UTC, TailsSavarin commented on app/javascript/components/Navbar.vue
> +const loginOpen = () => {
124 и 128

2022-11-26 19:13 UTC, Eelllllyy commented on app/javascript/components/DialogLoginOrSignUp.vue
> +              <input
Добавила один глазик , без закрытого

2022-11-26 19:20 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +const loginOpen = () => {
const loginOpen = () => {
  if (!storeAuth.isAuth) {
    storeAuth.loginOpen = !storeAuth.logOutOpen
  }
  else{
    storeAuth.logOutOpen = !storeAuth.loginOpen
  }
}

2022-11-26 19:20 UTC, Eelllllyy commented on app/javascript/components/Navbar.vue
> +const loginOpen = () => {
Что думаешь?

2022-11-30 21:55 UTC, merged